version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: home-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: home
      POSTGRES_USER: home_user
      POSTGRES_PASSWORD: home1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U home_user -d home" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"  # 최대 2개의 코어 할당
          memory: 2GB   # 최대 2GB 메모리 할당
    networks:
      - home

volumes:
  postgres-data:

networks:
  home:
