spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  batch:
    job:
      enabled: false
  profiles:
    default: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 967453245275-dp6khfskfjde7tqka1052tn6e16d30ve.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://api.homesearch.world/login/oauth2/code/google
            scope:
              - email
              - profile

          naver:
            client-id: XzRlyQ4L0ppLDF033_2g
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://api.homesearch.world/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email

          kakao:
            client-id: d29b89030ba79e976bc09d4d00e9c2fd
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://api.homesearch.world/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
              - profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none         # 기본은 none, 각 프로필에서 필요시 override
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        format_sql: true

  flyway:
    enabled: false           # 기본은 모두 OFF
    locations: classpath:db/migration

logging:
  level:
    root: info

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: home-local
    access-minutes: 30
  mail:
    from-name: 홈서비스

domain:
  frontend: ${FRONTEND_URL}

apis:
  data:
    base-url: https://apis.data.go.kr
    # 국토교통부_아파트 매매 실거래가 상세 자료
    apt-service-key: ${APT_SERVICE_KEY}
    apt-title-path: /1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev
    # 국토교통부_건축HUB_건축물대장정보 서비스:총괄표제부 조회
    bld-service-key: ${BLD_SERVICE_KEY}
    bld-title-path: /1613000/BldRgstHubService/getBrRecapTitleInfo
    # 국토교통부_건축HUB_건축물대장정보 서비스: 표제부 조회
    recap-title-path: /1613000/BldRgstHubService/getBrTitleInfo

odcloud:
  data:
    base-url: https://api.odcloud.kr
    od-service-key: ${ODC_SERVICE_KEY}
    # 한국부동산원_공동주택 단지 식별정보 기본 정보 조회 서비스
    apt-title-path: /api/AptIdInfoSvc/v1/getAptInfo
    # 한국부동산원_공동주택 단지 식별정보 동정보 조회 서비스
    dong-title-path: /api/AptIdInfoSvc/v1/getDongInfo

vworld:
  data:
    base-url: https://api.vworld.kr
    vw-service-key: ${VW_SERVICE_KEY}
    vm-domain: http://localhost:8080/only-local-test
    # 국토교통부_GIS_건물통합_WFS_조회
    vm-wfs-path: /ned/wfs/getBldgisSpceWFS
    # 2D데이터 API 2.0 레퍼런스
    vm-data-path: /req/data
