spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/home?reWriteBatchedInserts=true
    username: home_user
    password: ${DB_PASSWORD:home1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 32

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update

#  flyway:
#    enabled: true
#    locations: classpath:db/migration


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
  port: 8081

logging:
  level:
    root: info


