spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${RDS_HOST:localhost}:5432/home
    username: home_user
    password: ${RDS_PASSWORD:home1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 32

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: info

apis:
  data:
    base-url: https://apis.data.go.kr
    # 국토교통부_아파트 매매 실거래가 상세 자료
    apt-service-key: ${APT_SERVICE_KEY}
    apt-title-path: /1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev
    # 국토교통부_건축HUB_건축물대장정보 서비스:총괄표제부 조회
    bld-service-key: ${BLD_SERVICE_KEY}
    bld-title-path: /1613000/BldRgstHubService/getBrRecapTitleInfo

odcloud:
  data:
    base-url: https://api.odcloud.kr
    od-service-key: ${ODC_SERVICE_KEY}
    # 한국부동산원_공동주택 단지 식별정보 기본 정보 조회 서비스
    apt-title-path: /api/AptIdInfoSvc/v1/getAptInfo
    # 한국부동산원_공동주택 단지 식별정보 동정보 조회 서비스
    dong-title-path: /api/AptIdInfoSvc/v1/getDongInfo

vworld:
  data:
    base-url: https://api.vworld.kr
    # 국토교통부_GIS_건물통합_WFS_조회
    vw-service-key: ${VW_SERVICE_KEY}
    vw-title-path: /ned/wfs/getBldgisSpceWFS
    vm-domain: http://localhost:8080/only-local-test

